# Generated by Django 2.2.3 on 2019-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_post_starrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-starrate']},
        ),
    ]
