# Generated by Django 2.2.3 on 2019-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_auto_20190808_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart', models.CharField(max_length=3)),
            ],
        ),
    ]
