# Generated by Django 2.2.3 on 2019-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('area', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
