# Generated by Django 2.2.3 on 2019-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            name='location',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
