# Generated by Django 2.2.3 on 2019-08-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_post_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='tag_body',
        ),
    ]
