# Generated by Django 2.2.4 on 2019-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_auto_20190807_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='starrate',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
