# Generated by Django 2.2.3 on 2019-08-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_auto_20190807_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
        ),
    ]
