# Generated by Django 2.2.3 on 2019-08-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0006_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
