# Generated by Django 2.2.3 on 2019-08-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0008_feature_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Heart',
        ),
    ]
