# Generated by Django 2.2.3 on 2019-08-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_auto_20190808_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Location',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searchapp.Location'),
            preserve_default=False,
        ),
    ]
