# Generated by Django 2.2.3 on 2019-08-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0011_auto_20190809_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_body',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searchapp.Feature'),
            preserve_default=False,
        ),
    ]
