# Generated by Django 2.2.3 on 2019-08-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0013_auto_20190809_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='starrate',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
